### ISSUE TITLE
Put certificate to /system/etc/security/cacerts not really working

### ISSUE THREAD

**Issue by N-X-T** [vvb2060/zygisk_cacerts#1]
I tried leaving $MODPATH/system/etc/security/cacerts empty and installing the module, then I checked /system/etc/security/cacerts was empty but Setting -> Trusted credentials nothing changed.

MIUI Global 14.0.3
Android 13
Magisk Alpha: 8e82113b-alpha (27007)

**Comment by vvb2060** [comment]
Expected

**Comment by N-X-T** [comment]
For anyone who comes later and has the same problem as me: https://t.me/qianqianzhuang/31
